baseURL = "https://tandat-562.github.io/d963-blog/"
publishDir = "docs"
canonifyURLs = true
relativeURLs = false

languageCode = "vi"
title = "D963 - Blog lập trình mạng"
theme = "PaperMod"
[menu]
  [[menu.main]]
    name = "Trang chính"
    url = "#top"
    weight = 1
  [[menu.main]]
    name = "Về tôi"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "Kỹ năng"
    url = "#skills"
    weight = 3
  [[menu.main]]
    name = "Dự án"
    url = "#projects"
    weight = 4
  [[menu.main]]
    name = "Chứng chỉ"
    url = "#certs"
    weight = 5
  [[menu.main]]
    name = "Liên hệ"
    url = "#contact"
    weight = 6
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 7
[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  customCSS = ["custom.css"]
imageUrl = "avatar.jpg"
